import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        background: "#0b1326",
        surface: "#0b1326",
        "surface-dim": "#0b1326",
        "surface-bright": "#31394d",
        "surface-container-lowest": "#060e20",
        "surface-container-low": "#131b2e",
        "surface-container": "#171f33",
        "surface-container-high": "#222a3d",
        "surface-container-highest": "#2d3449",
        "surface-variant": "#2d3449",
        primary: "#d0bcff",
        "primary-container": "#a078ff",
        "primary-fixed": "#e9ddff",
        "primary-fixed-dim": "#d0bcff",
        "on-primary": "#3c0091",
        "on-primary-container": "#340080",
        "on-primary-fixed": "#23005c",
        "on-primary-fixed-variant": "#5516be",
        "inverse-primary": "#6d3bd7",
        secondary: "#c3c0ff",
        "secondary-container": "#3e3c8f",
        "secondary-fixed": "#e2dfff",
        "secondary-fixed-dim": "#c3c0ff",
        "on-secondary": "#272377",
        "on-secondary-container": "#afadff",
        "on-secondary-fixed": "#100563",
        "on-secondary-fixed-variant": "#3e3c8f",
        tertiary: "#e2c62d",
        "tertiary-container": "#c4ab01",
        "tertiary-fixed": "#ffe24c",
        "tertiary-fixed-dim": "#e2c62d",
        "on-tertiary": "#393000",
        "on-tertiary-container": "#4a3f00",
        "on-tertiary-fixed": "#211b00",
        "on-tertiary-fixed-variant": "#524600",
        "on-background": "#dae2fd",
        "on-surface": "#dae2fd",
        "on-surface-variant": "#cbc3d7",
        "inverse-surface": "#dae2fd",
        "inverse-on-surface": "#283044",
        "surface-tint": "#d0bcff",
        outline: "#958ea0",
        "outline-variant": "#494454",
        error: "#ffb4ab",
        "error-container": "#93000a",
        "on-error": "#690005",
        "on-error-container": "#ffdad6",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        unit: "8px",
        gutter: "24px",
        "margin-mobile": "16px",
        "margin-desktop": "48px",
        "section-gap": "80px",
        "container-max": "1280px",
      },
      maxWidth: {
        "container-max": "1280px",
      },
      fontFamily: {
        display: ["var(--font-display)", "Space Grotesk", "sans-serif"],
        "body-md": ["var(--font-body)", "Be Vietnam Pro", "sans-serif"],
        "body-lg": ["var(--font-body)", "Be Vietnam Pro", "sans-serif"],
        "label-caps": ["var(--font-display)", "Space Grotesk", "sans-serif"],
        h1: ["var(--font-display)", "Space Grotesk", "sans-serif"],
        h2: ["var(--font-display)", "Space Grotesk", "sans-serif"],
        h3: ["var(--font-display)", "Space Grotesk", "sans-serif"],
      },
      fontSize: {
        "body-md": ["16px", { lineHeight: "1.6", fontWeight: "400" }],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
        "label-caps": ["12px", { lineHeight: "1.2", letterSpacing: "0.1em", fontWeight: "700" }],
        h3: ["24px", { lineHeight: "1.4", fontWeight: "500" }],
        h2: ["32px", { lineHeight: "1.3", fontWeight: "600" }],
        h1: ["48px", { lineHeight: "1.2", fontWeight: "600" }],
        display: ["64px", { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "700" }],
      },
      keyframes: {
        "twinkle-pulse": {
          "0%, 100%": { opacity: "0.3", transform: "scale(1)" },
          "50%": { opacity: "1", transform: "scale(1.2)" },
        },
        "shooting-star": {
          "0%": { transform: "translateX(-100%) translateY(0)", opacity: "0" },
          "10%": { opacity: "1" },
          "90%": { opacity: "1" },
          "100%": { transform: "translateX(120vw) translateY(40vh)", opacity: "0" },
        },
      },
      animation: {
        "twinkle-pulse": "twinkle-pulse 4s infinite ease-in-out",
        "shooting-star": "shooting-star 6s linear infinite",
      },
    },
  },
  plugins: [],
};
export default config;
